### PR TITLE
Fix compilation errors that occurred by overloading file io functions…

### PR DESCRIPTION
**Pull request by MarioStanke**
… like fgetc, fputc, fwrite, ungetc, ftell to work both with uncompressed and compressed (gzip) files or streams.

### CODE REVIEW

**Comment by MarioStanke** [comment]
When trying to compile on an Ubuntu gcc version 13.3.0 I noticed many compiler errors like
cannot convert ‘gzFile’ {aka ‘gzFile_s*’} to ‘FILE*’
that seem to stem from calling functions written for uncompressed files on compressed files. I suspect older compilers were not as strict with type checking. With this pull-request, the test cases run through.
Greetings from Germany.

**Comment by MarioStanke** [comment]
I deleted the pull request as I had overlooked that `configure` overwrote the source files that I had changed. I now have a version that compiles on gcc version 13.3.0 if interested.
